#!/bin/sh

transset=$(which transset-df 2>/dev/null)
tmux=$(which tmux 2>/dev/null)
mutt=$(which mutt 2>/dev/null)
ranger=$(which ranger 2>/dev/null)

if [ -x "$transset" ];  then
    transset-df -a 0.88
fi

if [ ! -x "$tmux" ]; then
    echo "tmux is not installed"
    exit 
else
    tmux new-session -n 'terminal'
    tmux new-window
    tmux rename-window -t2 'ranger'
    tmux attach-session -d
fi
