#!/bin/sh

transset=$(which transset-df)
tmux=$(which tmux)
mutt=$(which mutt)
ranger=$(which ranger)

if [ -x "$transset" ] && [ -x "$tmux" ]; then
    transset-df -a 0.78
    tmux new-session -d 
    if [ -x "$ranger" ]; then
        tmux new-window 'ranger'
    fi
    if [ -x "$mutt" ]; then
        tmux new-window 'mutt'
    fi
    tmux select-window -t 1
    tmux -2 attach-session -d
else 
    echo "missing a necessary piece of software"
fi
