#!/usr/bin/bash

src=$1
dest=$2
doc=${src%.*}

if [ ! -x "$1" ]; then
    echo "the source file does not appear to exist"
    exit 1
fi

if [ "$dest" == "" ]; then
    dest="$doc".txt
fi

unzip -p "$doc".docx | sed -e 's/<\/w:p>/\n/g; s/<[^>]\{1,\}>//g; s/[^[:print:]\n]\{1,\}//g' > "$dest"
