#!/usr/bin/sh

now=$(date)
yaourt=$(which yaourt)
ag=$(which ag)
rclone=$(which rclone)
pip=$(which pip)
installed=/tmp/installed.md

localBin() {
    for f in /usr/local/bin/* ; do
        find ~/.cabal/share/doc/x86_64-linux-ghc-7.10.3/ -type d -printf '%f\n'
    done 
}

printTitle() {
    printf "**Installed Software %s**\n\n" "$now" > "$installed"
}

set -e
printTitle
if [ -x "$yaourt" ] && [ -x "$ag" ]; then
    { yaourt -Qe; 
        localBin; } >> "$installed"
else
    echo "yaourt not installed"
fi

if [ -x "$pip" ]; then
    { "$pip" list; } >> "$installed"
fi

if [ -x "$rclone" ]; then
    rclone copy "$installed" gdrive:docs && echo "successfully transferred to google drive.." && rm "$installed" &&
    echo ".. and removed from tmp directory"
else
    echo "unable to transfer file"
fi
