#!/usr/bin/sh

now=$(date)
yaourt=$(which yaourt 2>/dev/null)
rg=$(which rg 2>/dev/null)
rclone=$(which rclone 2>/dev/null)
pip=$(which pip 2>/dev/null)
#opam=$(which opam 2>/dev/null)
installed=/tmp/installed.md

cabalInstalls() {
    ls "$HOME/.cabal/bin"
}

stackInstalls() {
    ls "$HOME/.local/bin"
}

#opamInstalls() {
    #if [ -x "$opam" ]; then
        #opam list | cut -d' ' -f1 | tail -n +2
    #fi
#}

printTitle() {
    printf "**Installed Software %s**\n\n" "$now" > "$installed"
}

set -e
printTitle
if [ -x "$yaourt" ] && [ -x "$rg" ]; then
    yaourt -Qe >> "$installed"
    stackInstalls >> "$installed"
    cabalInstalls >> "$installed"
    #opamInstalls >> "$installed"
else
    echo "yaourt not installed"
fi

if [ -x "$pip" ]; then
    { "$pip" list --format=legacy; } >> "$installed"
fi

if [ -x "$rclone" ]; then
    rclone copy "$installed" gdrive:docs && echo "successfully transferred to google drive.." && rm "$installed" &&
    echo ".. and removed from tmp directory"
else
    echo "unable to transfer file"
fi
