#!/usr/bin/sh

now=$(date)
yaourt=$(which yaourt)
ag=$(which ag)
rclone=$(which rclone)
pip=$(which pip)
opam=$(which opam)
installed=/tmp/installed.md

#cabalInstalls() {
    #if [ -f '/home/david/.cabal/world' ]; then
        #cut -d' ' -f1 '/home/david/.cabal/world'
    #fi
#}

stackInstalls() {
    ls "$HOME/.local/bin"
}

opamInstalls() {
    if [ -x "$opam" ]; then
        opam list | cut -d' ' -f1 | tail -n +2
    fi
}

printTitle() {
    printf "**Installed Software %s**\n\n" "$now" > "$installed"
}

set -e
printTitle
if [ -x "$yaourt" ] && [ -x "$ag" ]; then
    yaourt -Qe >> "$installed"
    stackInstalls >> "$installed"
    opamInstalls >> "$installed"
else
    echo "yaourt not installed"
fi

if [ -x "$pip" ]; then
    { "$pip" list --format=legacy; } >> "$installed"
fi

if [ -x "$rclone" ]; then
    rclone copy "$installed" gdrive:docs && echo "successfully transferred to google drive.." && rm "$installed" &&
    echo ".. and removed from tmp directory"
else
    echo "unable to transfer file"
fi
