#!/usr/bin/sh

pip=$(which pip)
pkg=$(which ghc-pkg)
pacman=$(which pacman)

cd $HOME/Documents || exit 1

if [ -x "$pacman" ]; then
    $pacman -Q > all_packages
else
    echo -e "\e[31mcannot find pacman, exiting...\e[0m"
    exit 1
fi 

if [ -x "$pip" ]; then
    $pip list >> all_packages
else
    echo -e "\e[31mcannot find pip, exiting...\e[0m"
    if [ -e all_packages ]; then
        echo 
        rm all_packages
    fi
fi

if [ -x "$pkg" ]; then
    $pkg list | awk '/home/{p=1}p' | sed -r '/home/d; s/\s+(.*)/\1/; /^$/d' >> all_packages
fi
