#!/bin/bash

drive="$1"

if [ "$1" == "" ]; 
then 
    echo "no drive supplied" 
    exit
fi

if [ ! -d "/Volumes/NTFS" ]
then
    sudo mkdir /Volumes/NTFS/
fi

if [ -e "$drive" ]
then
    printf "found %s\\n" "$drive"
    ntfs=$(diskutil list | rg -i ntfs | awk '{print $NF}')
    if [ "$ntfs" = "" ]
    then 
        echo "No NTFS drive found"
        exit
    fi
    mounted=$(df | rg "$ntfs")
    if [ "$mounted" = "" ]
    then 
        sudo ntfs-3g "$drive" /Volumes/NTFS/ -olocal -oallow_other
        printf "%s successfully mounted read/write\\n" "$drive"
    else 
        printf "unmounting %s\\n" "$drive" 
        sudo umount "$drive"
        sudo ntfs-3g "$drive" /Volumes/NTFS/ -olocal -oallow_other
        printf "%s successfully mounted read/write\\n" "$drive"
    fi
else
    printf "drive %s does not exist\\n" "$1"
    exit
fi
