#!/usr/bin/bash

today=$(date +%B_%d)
wiki='https://en.wikipedia.org/wiki/'
cache=~/.cache/onthisday-"$today"

if [ -f "$cache" ] && [ "$(basename "$cache" | sed 's/.*-//')" == "$today" ]; then
    # file exists and is up-to-date, so do nothing
    exit
else
    # if no file exists at all
    find ~/.cache -type f -name 'onthisday*' -exec rm {} +
    w3m -cols 999 -dump "$wiki""$today" | sed -n '/Events/,/Births/p' | sed '/^$/d' | sed '/Events/d' | sed '/Births/d' >> "$cache"
fi
