#!/usr/bin/bash

if [ "$(id -u)" != 0 ]; then
    echo "This script requires root permission"
    sudo "$0"
    exit
else
    cd /etc/pacman.d || exit

    if [ -e mirrorlist ]; then
        mv mirrorlist mirrorlist.old
    fi

    mv mirrorlist.pacnew mirrorlist

    sed -i '/United Kingdom/,/^$/s/#//' mirrorlist

    printf "\e[1mThe pacman mirrorlist has been successfully updated\e[0m\n"
fi

