#!/usr/bin/bash

now=$(date)
number=$1

if [ -x "$HOME/Documents/text/diary.md" ]; then
    printf "rang 101 on %s after seeing %s people dealing.\n" "$now" "$number" >> "$HOME/Documents/text/diary.md"
else
    touch "$HOME/Documents/text/diary.md"
    printf "rang 101 at %s after seeing %s people dealing.\n" "$now" "$number" >>  "$HOME/Documents/text/diary.md"
fi 
