#! /bin/bash

# non-recursive version: 'for itm in *'
for itm in /home/david/**/*
do
    if [ -h "$itm" ]
    then
        echo "$itm found"
        target=$(readlink -fn "$itm")
        if [ ! -e "$target" ]
        then
            echo "$itm"
            rm "$itm"
        fi
    fi
done
