#! /bin/bash

for itm in "$HOME/**/*"; do
    if [ -h "$itm" ]
    then
        printf '\e[33m%s\e[0m\n' "$itm found"
        target=$(readlink -fn "$itm")
        if [ ! -e "$target" ]
        then
            echo "$itm"
            rm "$itm"
        fi
    fi
done
