#!/usr/bin/sh

cd ~/.xmonad/scripts || exit

rm -r ~/.xmonad/scripts/bin/*

for file in *.hs; do
    name=$(echo "$file" | cut -d'.' -f1)
    ghc -O2 -dynamic -threaded -o "$name" "$file"
    mv "$name" ~/.xmonad/scripts/bin
done

for file in *.o; do
    rm "$file"
done

for file in *.hi; do
    rm "$file"
done

cd - || exit

xmonad --recompile
