#!/usr/bin/bash

junkfiles=(
    "$HOME/.recently-used" 
    "$HOME/.local/share/recently-used.xbel" 
    "$HOME/.bzr.log" 
    "$HOME/.thumbnails" 
    "$HOME/.gconfd" 
    "$HOME/.gconf"
    "$HOME/.gstreamer-0.10"
    "$HOME/.esd_auth"
    "$HOME/.python_history"
    "$HOME/.local/share/zathura/input-history"
    "$HOME/.ghc/ghci_history"
    "$HOME/.pythonhist"
    "$HOME/.lesshst"
    "$HOME/.sqlite_history"
    "$HOME/.config/nvim/.netrwhist"
    "$HOME/.nvimlog"
    "$HOME/.node_repl_history"
    "$HOME/.scala_history"
    "$HOME/.thumbnails"
)

found=()
hist=() # microML leaves history files all over the place!
response='n'

search_for_files() {
    for i in "${junkfiles[@]}"; do
        if [ -f "${i}" ]; then
            found+=("${i}")
        fi
    done
    hist+=$(find ~/ -type f -name ".history")
}

print_files() {
    if [ "${#found}" -eq 0 ] && [ "${#hist}" -eq 0 ]; then
        printf '\e[32m%s\e[0m\n' "No junk files found"
        exit
    else
        printf '\e[1;32m%s\e[0m\n' "The following junk files were found:" 
        printf '\e[31m%s\e[0m\n' "${found[@]}"

        if [ "${#hist}" -ne 0 ]; then
                printf '\e[31m%s\e[0m\n' "${hist[@]}"
        fi
        dispatch
    fi
}

dispatch() {
    printf '\e[1m%s\e[0m\n' "Would you like to delete these files [y/n]"
    read -r response
    while [[ ! "${response}" || "${response}" = *[^yYnN]* ]]; do
        printf '\e[31m%s\e[0m\n' "Incorrect entry. Please try again:"
        read -r response
    done
    if [[ "$response" = *[yY]* ]]; then
        delete_files
    else
        exit
    fi
}

delete_files() {
    printf '\e[31m%s\n' "deleting..."
    for i in "${found[@]}"; do
        rm "${i}"
    done
    if [ "${#hist}" -ne 0 ]; then
        xargs rm <<< "${hist[@]}"
    fi
    printf '\e[32m%s\n' "Done!"
}

search_for_files && print_files
