#!/usr/bin/env python3

import os
import shutil


shittyfiles = [
    '~/.recently-used',
    '~/.local/share/recently-used.xbel',
    '~/.bzr.log',
    '~/.thumbnails',
    '~/.gconfd',
    '~/.gconf',
    '~/.gstreamer-0.10',
    '~/.esd_auth',
    '~/.python_history',
    '~/.local/share/zathura/input-history',
    '~/.lein/repl-history',
    '~/.ghc/ghci_history',
    '~/.pythonhist',
    '~/.gambc_history',
    '~/.node_repl_history',
    '~/.lesshst',
    '~/.jline-jython.history'
]


def yesno(question, default="n"):
    """ Asks the user for YES or NO, always case insensitive.
        Returns True for YES and False for NO.
    """
    prompt = "%s (y/[n]) " % question

    ans = input(prompt).strip().lower()

    if not ans:
        ans = default

    if ans == "y":
        return True
    return False


def rmshit():
    found = []
    for f in shittyfiles:
        absf = os.path.expanduser(f)
        if os.path.exists(absf):
            found.append(absf)
            print("    %s" % f)

    if len(found) == 0:
        print("No useless files found :)")
        return

    print("Found the following: ")
    if yesno("Remove all?", default="n"):
        for f in found:
            if os.path.isfile(f):
                os.remove(f)
            else:
                shutil.rmtree(f)
        print("All cleaned")
    else:
        print("No file removed")


if __name__ == '__main__':
    rmshit()
