#!/run/current-system/sw/bin/bash

watch_folder=~/.torrent/watch
cd $watch_folder || exit
[[ "$1" =~ xt=urn:btih:([^&/]+) ]] || exit;
echo "d10:magnet-uri${#1}:${1}e" > "meta-${BASH_REMATCH[1]}.torrent"
