#!/run/current-system/sw/bin/bash

printf "On this day:\n %s" "$(shuf -n1  ~/.cache/onthisday-*)" | fmt -80 -s | \
    $(shuf -n1 -e cowsay cowthink) -"$(shuf -n1 -e b d g p s t w y)" -f \
    "$(shuf -n1 -e $(cowsay -l | tail -n -2))"
