#!/bin/bash

printf "On this day:\n %s" "$(gshuf -n1  ~/.cache/onthisday-*)" | fmt -80 -s | \
    $(gshuf -n1 -e cowsay cowthink) -"$(gshuf -n1 -e b d g p s t w y)" -f \
    "$(gshuf -n1 -e $(cowsay -l | tail -n -2))"
